# frozen_string_literal: true

module ParseReviews
  FAKE_THRESHOLD = 40
  UNCERTAIN_THRESHOLD = 20

  FAKE_SIGNAL_KEYS = %w[
    THIN_ACCOUNT_0 THIN_ACCOUNT_1 SHORT_TEXT_EXTREME SHORT_TEXT
    BURST_AFTER_NEGATIVE FIVE_STAR_EMPTY SURNAME_REPEAT GENERIC_TEXT
    SUSPICIOUS_NEGATIVE MARKETING_TONE EMOJI_SPAM TEMPLATE_CLONE
    ALL_POSITIVE REPEATABLE_PLUSES_2 REPEATABLE_PLUSES_3 BUSINESS_NAME_DROP
  ].freeze

  REAL_SIGNAL_KEYS = %w[
    EDITED_REVIEW HAS_PHOTOS EXPERIENCED_AUTHOR_5 EXPERIENCED_AUTHOR_10
    ACTIVE_PROFILE LONG_TEXT SPECIFIC_DETAILS BALANCED_TONE NATURAL_LANGUAGE
    LOCAL_GUIDE OWNER_RESPONDED HELPFUL_VOTES
  ].freeze
end
