default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gftr_development

test:
  <<: *default
  database: gftr_test

production:
  <<: *default
  database: gftr_production
  username: gftr
  password: <%= ENV["DATABASE_PASSWORD"] %>
